# Generated by Django 3.2.13 on 2022-07-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('ship_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('ship_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
