# Generated by Django 3.2.13 on 2022-07-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aib_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameOptions',
        ),
    ]
