# Generated by Django 3.2.13 on 2022-07-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aib_site', '0002_delete_gameoptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ships',
            new_name='Ship',
        ),
    ]
