# Generated by Django 3.2.13 on 2022-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aib_site', '0003_rename_ships_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='ship_description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
