# Generated by Django 3.2.13 on 2022-07-31 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aib_site', '0004_ship_ship_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
