# Generated by Django 3.2.13 on 2022-07-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aib_site', '0005_delete_ship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('ship_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('ship_name', models.CharField(max_length=200, unique=True)),
                ('ship_description', models.TextField(max_length=500)),
            ],
        ),
    ]
