# Generated by Django 3.2.13 on 2022-08-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aib_site', '0006_ship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
