# Generated by Django 3.2.13 on 2022-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aib_site', '0009_ship_ship_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='ship_displayName',
            field=models.CharField(max_length=200),
        ),
    ]
