# Generated by Django 3.2.13 on 2022-09-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aib_site', '0010_alter_ship_ship_displayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battlesite',
            fields=[
                ('site_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('site_name', models.CharField(max_length=200, unique=True)),
                ('site_displayName', models.CharField(max_length=200)),
                ('site_description', models.TextField(max_length=500)),
            ],
        ),
    ]
