# Generated by Django 3.2.13 on 2022-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aib_site', '0011_battlesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('bullet_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('bullet_name', models.CharField(max_length=200, unique=True)),
                ('bullet_displayName', models.CharField(max_length=200)),
                ('bullet_description', models.TextField(max_length=500)),
            ],
        ),
    ]
