# Generated by Django 3.2.13 on 2022-09-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aib_site', '0012_bullet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invader',
            fields=[
                ('invader_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('invader_name', models.CharField(max_length=200, unique=True)),
                ('invader_displayName', models.CharField(max_length=200)),
                ('invader_description', models.TextField(max_length=500)),
            ],
        ),
    ]
