# Generated by Django 3.2.13 on 2022-09-26 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aib_site', '0013_invader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('highScore', models.IntegerField(default=0)),
                ('lastLevel', models.IntegerField(default=1)),
                ('gameDate', models.CharField(max_length=10)),
                ('gameTime', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
